config/routes.rb
Rails.application.routes.draw do
  # get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  resources :users

  # get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'

  get '/shops', to: 'shops#index'
  # resources :shops

  # resources :admin
  scope :admin do
    resources :categories
  end


  root 'shops#index'
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
  layout 'admin'

  def index
  end

  def show
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  private
    def logged_in_user
      unless logged_in?
        redirect_to login_url
      end
    end

    def admin_user
      user = User.find_by id: session[:user_id]
      unless is_admin?(user.email)
        redirect_to root_url
      end
    end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  layout 'admin'
  before_action :admin_user
  before_action :logged_in_user

  def index
    @categories = Category.all
  end

  def show
  end

  def new
  end

  def edit
  end

  def update
  end

  def create
    @category = Category.new(category_params)
    if @category.save
      flash[:success] = "Thêm thành công"
      redirect_to categories_url
    else
      flash[:danger] = "Thêm không thành công"
      redirect_to categories_url
    end
  end

  private
    def category_params
      params.require(:category).permit(:name)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create
    user = User.find_by email: params[:session][:email].downcase
    if user && user.authenticate(params[:session][:password])
      log_in user
      if is_admin?(params[:session][:email])
        redirect_to categories_url
      else
        redirect_to root_url
      end
    else
      flash[:danger] = "Đăng nhập thất bại"
      redirect_to root_url
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
  def show
  end

  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :show]
  before_action :correct_user, only: [:edit, :update]

  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      log_in @user
      flash[:success] = "Tạo tài khoản thành công"
      redirect_to root_url
    else
      flash[:danger] = "Tạo tài khoản thất bại"
      redirect_to root_url
    end
  end

  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(update_user_params)
      redirect_to @user
    else
      render 'edit'
    end
  end

  def show
    @user = User.find(params[:id])
  end

  private
    def user_params
      params.require(:user).permit(:password, :email, :fullname, :password_confirmation)
    end

    def update_user_params
      parmas.require(:user).permit(:fullname)
    end

    def correct_user
      @user = User.find(params[:id])
      redirect_to(root_url) unless current_user?(@user)
    end
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def log_in(user)
    session[:user_id] = user.id
  end

  def current_user
    if session[:user_id]
      @current_user ||= User.find_by id: session[:user_id]
    elsif cookies.signed[:user_id]
      user = User.find_by id: cookies.signed[:user_id]
      if user
        log_in user
        @current_user = user
      end
    end
  end

  def is_admin?(email)
    user = User.find_by email: email
    user.admin
  end

  def logged_in?
    !current_user.nil?
  end

  def forget(user)
    cookies.delete(:user_id)
  end

  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/shops_helper.rb
module ShopsHelper
end

app/views/categories/index.html.erb
<%= provide(:title, "Loại hàng") %>
<h1 class="h3 mb-2 text-gray-800">Category</h1>

<!-- Add category modal -->
<button type="button" class="btn btn-primary mb-2" data-toggle="modal" data-target="#categoryModal">
  Thêm loại hàng
</button>

<!-- Add category Modal -->
<div class="modal fade" id="categoryModal" tabindex="-1" role="dialog" aria-labelledby="categoryModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title" id="categoryModalLabel">Thêm loại hàng</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
        <%= form_for :category, url: categories_url do |f| %>
          <%= f.label "Thể loại" %>
          <%= f.text_field :name, class: 'form-control' %>
          <br>
          <%= f.submit "Thêm", class: 'btn btn-primary' %>
        <% end %>
      </div>
    </div>
  </div>
</div>

<div class='row'>
  <table class="table table-striped table-bordered">
    <thead>
      <tr>
        <td>Tên</td>
        <td>*</td>
      </tr>
    </thead>
    <tbody>
      <% @categories.each do |category| %>
        <tr>
          <td>
            <%= category.name %>
          </td>
          <td>
            <center>
              <%= link_to "Sửa", edit_category_path(category), class: 'btn btn-primary' %>
              <button class="btn btn-danger">Xóa</button></center>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
<div class='alert alert-<%= message_type %>'><%= message %></div>
<% end %>

app/views/layouts/admin.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag    'admin/application' %>
    <%= javascript_include_tag 'admin/application' %>
  </head>

  <body id="page-top">
    <div id="wrapper">
      <%= render 'layouts/admin/sidebar' %>
      <div id="content-wrapper" class="d-flex flex-column">
        <div id="content">
          <%= render 'layouts/admin/header' %>
          <div class="container-fluid">
            <%= yield %>
          </div>
        </div>
        <%= render 'layouts/admin/footer' %>
      </div>
    </div>
  </body>
</html>

app/views/layouts/admin/_footer.html.erb
<footer class="sticky-footer bg-white">
  <div class="container my-auto">
    <div class="copyright text-center my-auto">
      <span>Copyright © Your Website 2019</span>
    </div>
  </div>
</footer>

app/views/layouts/admin/_header.html.erb
<nav class="navbar navbar-expand navbar-light bg-white topbar mb-4 static-top shadow">

  <button id="sidebarToggleTop" class="btn btn-link d-md-none rounded-circle mr-3">
    <i class="fa fa-bars"></i>
  </button>

  <ul class="navbar-nav ml-auto">
    <div class="topbar-divider d-none d-sm-block"></div>
    <li class="nav-item dropdown no-arrow">
      <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
        <span class="mr-2 d-none d-lg-inline text-gray-600 small">Valerie Luna</span>
        <img class="img-profile rounded-circle" src="https://source.unsplash.com/QAB-WJcbgJk/60x60">
      </a>
      <div class="dropdown-menu dropdown-menu-right shadow animated--grow-in" aria-labelledby="userDropdown">
        <a class="dropdown-item" href="#">
          <i class="fa fa-user fa-sm fa-fw mr-2 text-gray-400"></i>
          Profile
        </a>
        <a class="dropdown-item" href="#">
          <i class="fa fa-cogs fa-sm fa-fw mr-2 text-gray-400"></i>
          Settings
        </a>
        <a class="dropdown-item" href="#">
          <i class="fa fa-list fa-sm fa-fw mr-2 text-gray-400"></i>
          Activity Log
        </a>
        <div class="dropdown-divider"></div>
        <%= link_to "Log out", logout_path, method: :delete, class: 'dropdown-item' %>
      </div>
    </li>

  </ul>

</nav>

app/views/layouts/admin/_sidebar.html.erb
<ul class="navbar-nav bg-gradient-primary sidebar sidebar-dark accordion" id="accordionSidebar">
  <a class="sidebar-brand d-flex align-items-center justify-content-center" href="index.html">
    <div class="sidebar-brand-icon rotate-n-15">
      <i class="fas fa-laugh-wink"></i>
    </div>
    <div class="sidebar-brand-text mx-3">SB Admin <sup>2</sup></div>
  </a>
  <hr class="sidebar-divider my-0">
  <li class="nav-item active">
    <a class="nav-link" href="index.html">
      <i class="fas fa-fw fa-tachometer-alt"></i>
      <span>Dashboard</span></a>
  </li>
  <hr class="sidebar-divider">
  <div class="sidebar-heading">
    Interface
  </div>
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseTwo" aria-expanded="true" aria-controls="collapseTwo">
      <i class="fa fa-fw fa-cog"></i>
      <span>Components</span>
    </a>
    <div id="collapseTwo" class="collapse" aria-labelledby="headingTwo" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Custom Components:</h6>
        <a class="collapse-item" href="buttons.html">Buttons</a>
        <a class="collapse-item" href="cards.html">Cards</a>
      </div>
    </div>
  </li>
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapseUtilities" aria-expanded="true" aria-controls="collapseUtilities">
      <i class="fa fa-fw fa-wrench"></i>
      <span>Utilities</span>
    </a>
    <div id="collapseUtilities" class="collapse" aria-labelledby="headingUtilities" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Custom Utilities:</h6>
        <a class="collapse-item" href="utilities-color.html">Colors</a>
        <a class="collapse-item" href="utilities-border.html">Borders</a>
        <a class="collapse-item" href="utilities-animation.html">Animations</a>
        <a class="collapse-item" href="utilities-other.html">Other</a>
      </div>
    </div>
  </li>
  <hr class="sidebar-divider">
  <div class="sidebar-heading">
    Addons
  </div>
  <li class="nav-item">
    <a class="nav-link collapsed" href="#" data-toggle="collapse" data-target="#collapsePages" aria-expanded="true" aria-controls="collapsePages">
      <i class="fa fa-fw fa-folder"></i>
      <span>Pages</span>
    </a>
    <div id="collapsePages" class="collapse" aria-labelledby="headingPages" data-parent="#accordionSidebar">
      <div class="bg-white py-2 collapse-inner rounded">
        <h6 class="collapse-header">Login Screens:</h6>
        <a class="collapse-item" href="login.html">Login</a>
        <a class="collapse-item" href="register.html">Register</a>
        <a class="collapse-item" href="forgot-password.html">Forgot Password</a>
        <div class="collapse-divider"></div>
        <h6 class="collapse-header">Other Pages:</h6>
        <a class="collapse-item" href="404.html">404 Page</a>
        <a class="collapse-item" href="blank.html">Blank Page</a>
      </div>
    </div>
  </li>
  <hr class="sidebar-divider d-none d-md-block">
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JustDoIt</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'layouts/shop/header' %>
    <br>
    <br>
    <div class='container'>
      <div class='row'>
        <%= render 'layouts/shop/sidebar' %>
        <div class='col-lg-9'>
          <br>
          <%= render 'layouts/flash' %>
          <%= yield %>
        </div>
      </div>
    </div>
  </body>
</html>

app/views/layouts/login.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/layouts/shop/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-dark fixed-top">
  <div class="container">
    <a class="navbar-brand" href="#">Start Bootstrap</a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ml-auto">
        <li class="nav-item active">
          <a class="nav-link" href="#">Home</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Services</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="#">Contact</a>
        </li>
        <% if logged_in? %>
          <li class='nav-item'>
            <%= link_to "User", edit_user_path(current_user), class: 'nav-link' %>
          </li>
          <li class='nav-item'>
            <%= link_to "Log out", logout_path, method: :delete, class: 'nav-link' %>
          </li>
        <% else %>
          <li class='nav-item'>
            <a style='cursor: pointer' class='nav-link' data-toggle="modal" data-target="#login">
              Đăng nhập
            </a>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</nav>
<!-- Modal -->
<div class="modal fade" id="login" tabindex="-1" role="dialog" aria-labelledby="loginLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-body">
        <nav>
          <div class="nav nav-tabs" id="nav-tab" role="tablist">
            <a href="#nav-login" class="nav-item nav-link active" id='nav-login-tab' data-toggle='tab' role='tab' aria-controls='nav-login' aria-selected='true'>
              Đăng nhập
            </a>
            <a href="#nav-register" class="nav-item nav-link" id="nav-register-tab" data-toggle='tab' role='tab' aria-controls='nav-register' aria-selected='false'>Đăng ký</a>
          </div>
        </nav>
        <div class="tab-content" id="nav-tabContent">
          <div class="tab-pane fade show active" id="nav-login" role='tabpanel' aria-labelledby='nav-login-tab'>
            <%= form_for :session, url: login_path do |f| %>
              <%= f.label :email %>
              <%= f.email_field :email, class: 'form-control' %>

              <%= f.label :password %>
              <%= f.password_field :password, class: 'form-control' %>
              <br>
              <center>
                <%= f.submit "Đăng nhập", class: 'btn btn-primary' %>
              </center>
            <% end %>
          </div>
          <div class="tab-pane fade" id="nav-register" role='tabpanel' aria-labelledby='nav-register-tab'>
            <%= form_for :user, url: signup_path do |f| %>
              <%= f.label :email %>
              <%= f.email_field :email, class: 'form-control' %>

              <%= f.label :fullname %>
              <%= f.text_field :fullname, class: 'form-control' %>

              <%= f.label :password %>
              <%= f.password_field :password, class: 'form-control' %>

              <%= f.label :password_confirmation, "Nhập lại mật khẩu" %>
              <%= f.password_field :password_confirmation, class: 'form-control' %>
              <br>
              <center>
                <%= f.submit "Đăng ký", class: 'btn btn-primary' %>
              </center>
            <% end %>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/layouts/shop/_sidebar.html.erb
<div class="col-lg-3">
  <h1 class="my-4">Shop Name</h1>
  <div class="list-group">
    <a href="#" class="list-group-item">Category 1</a>
    <a href="#" class="list-group-item">Category 2</a>
    <a href="#" class="list-group-item">Category 3</a>
  </div>
</div>

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <div id='error_explanation'>
    <div class='alert alert-danger'>
      <%= t "alert.form", err: pluralize(object.errors.count, t("error")) %>
    </div>
    <ul>
      <% object.errors.full_message.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/shops/index.html.erb
<%= provide(:title, "") %>
<div id="carouselExampleIndicators" class="carousel slide my-4" data-ride="carousel">
  <ol class="carousel-indicators">
    <li data-target="#carouselExampleIndicators" data-slide-to="0" class=""></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="1" class="active"></li>
    <li data-target="#carouselExampleIndicators" data-slide-to="2" class=""></li>
  </ol>
  <div class="carousel-inner" role="listbox">
    <div class="carousel-item">
      <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="First slide">
    </div>
    <div class="carousel-item active">
      <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Second slide">
    </div>
    <div class="carousel-item">
      <img class="d-block img-fluid" src="http://placehold.it/900x350" alt="Third slide">
    </div>
  </div>
  <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
    <span class="carousel-control-prev-icon" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
    <span class="carousel-control-next-icon" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
</div>
<div class='row'>
  <div class="col-lg-4 col-md-6 mb-4">
    <div class="card h-100">
      <a href="#"><img class="card-img-top" src="http://placehold.it/700x400" alt=""></a>
      <div class="card-body">
        <h4 class="card-title">
          <a href="#">Item One</a>
        </h4>
        <h5>$24.99</h5>
        <p class="card-text">Lorem ipsum dolor sit amet, consectetur adipisicing elit. Amet numquam aspernatur!</p>
      </div>
      <div class="card-footer">
        <small class="text-muted">★ ★ ★ ★ ☆</small>
      </div>
    </div>
  </div>
</div>

app/views/users/edit.html.erb
<%= provide(:title, "Thông tin người dùng") %>
<%= form_for @user, url: edit_user_path do |f| %>
  <%= f.label :fullname %>
  <%= f.text_field :fullname %>
  <%= f.submit "Lưu" %>
<% end %>

app/views/users/new.html.erb
<%= provide(:title, "Đăng ký") %>

app/views/users/show.html.erb
<%= provide(:title, "Người dùng") %>
<h3>User</h3>
<%= link_to "Đăng xuất", logout_path, method: :delete %>